name = "youtube-alchemist-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "youtube_alchemist_db"
database_name = "youtube-alchemist-db"
database_id = "b0ac1191-230c-451d-8f33-5156890ddd8d"
